/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author LocalUser
 */
public class NewGuiALT extends javax.swing.JFrame {

  /**
   * Creates new form NewGui
   */
  public NewGuiALT(ControllerMainALT listener) {
    initComponents();
    eStop.addActionListener(listener);
    dataRequestButton.addActionListener(listener);
    disableBumperSwitch.addItemListener(listener);
    armPotOverride.addItemListener(listener);
    
    this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        infoWindow = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        eStop = new javax.swing.JButton();
        feedbackFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        battVoltField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mainBattLED = new javax.swing.JRadioButton();
        connLED = new javax.swing.JRadioButton();
        arduinoLED = new javax.swing.JRadioButton();
        otherLED = new javax.swing.JRadioButton();
        error1LED = new javax.swing.JRadioButton();
        error2LED = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        heartFrame = new javax.swing.JInternalFrame();
        heartMonitor = new javax.swing.JTextField();
        disableBumperSwitch = new javax.swing.JToggleButton();
        armPotOverride = new javax.swing.JToggleButton();
        dataRequestButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LunaBot");

        infoWindow.setAutoscrolls(true);
        infoWindow.setName(""); // NOI18N

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setText("Welcome to the LUNABOT");
        textArea.setToolTipText("");
        infoWindow.setViewportView(textArea);

        eStop.setBackground(new java.awt.Color(255, 0, 0));
        eStop.setText("Emergency Stop");

        feedbackFrame.setTitle("Robot Feedback");
        feedbackFrame.setVisible(true);

        jLabel1.setText("Main Battery_______________________");

        jLabel2.setText("LEDs_____________________________");

        mainBattLED.setText("Main Battery");

        connLED.setText("Connection");

        arduinoLED.setText("Arduino?");

        otherLED.setText("Something Else");

        error1LED.setText("Error 1");

        error2LED.setText("Error 2");

        jInternalFrame1.setTitle("Arm Position");
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout feedbackFrameLayout = new javax.swing.GroupLayout(feedbackFrame.getContentPane());
        feedbackFrame.getContentPane().setLayout(feedbackFrameLayout);
        feedbackFrameLayout.setHorizontalGroup(
            feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(battVoltField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackFrameLayout.createSequentialGroup()
                        .addGroup(feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainBattLED, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arduinoLED)
                            .addComponent(error1LED))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error2LED)
                            .addComponent(otherLED)
                            .addComponent(connLED, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1))
                .addContainerGap())
        );
        feedbackFrameLayout.setVerticalGroup(
            feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackFrameLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(battVoltField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainBattLED)
                    .addComponent(connLED))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherLED)
                    .addComponent(arduinoLED, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feedbackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error1LED)
                    .addComponent(error2LED))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        heartFrame.setTitle("Heart Monitor");
        heartFrame.setVisible(true);

        heartMonitor.setText("------------------------------------");

        javax.swing.GroupLayout heartFrameLayout = new javax.swing.GroupLayout(heartFrame.getContentPane());
        heartFrame.getContentPane().setLayout(heartFrameLayout);
        heartFrameLayout.setHorizontalGroup(
            heartFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heartMonitor)
        );
        heartFrameLayout.setVerticalGroup(
            heartFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heartMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        disableBumperSwitch.setText("Disable Bumper Switch");

        armPotOverride.setText("Arm Pot Overried");

        dataRequestButton.setText("Request Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heartFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(armPotOverride, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(disableBumperSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(dataRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(feedbackFrame)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eStop, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(disableBumperSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(armPotOverride, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heartFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(feedbackFrame)))
                    .addComponent(infoWindow))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton arduinoLED;
    public javax.swing.JToggleButton armPotOverride;
    public javax.swing.JTextField battVoltField;
    public javax.swing.JRadioButton connLED;
    public javax.swing.JButton dataRequestButton;
    public javax.swing.JToggleButton disableBumperSwitch;
    public javax.swing.JButton eStop;
    public javax.swing.JRadioButton error1LED;
    public javax.swing.JRadioButton error2LED;
    public javax.swing.JInternalFrame feedbackFrame;
    public javax.swing.JInternalFrame heartFrame;
    public javax.swing.JTextField heartMonitor;
    public javax.swing.JScrollPane infoWindow;
    public javax.swing.JFrame jFrame1;
    public javax.swing.JInternalFrame jInternalFrame1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton mainBattLED;
    public javax.swing.JRadioButton otherLED;
    public javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    
  public synchronized void heartUpdate(String s)
  {
    heartMonitor.setText(s + heartMonitor.getText().substring(0, 28));
  }
  
  public void addText(String newText) 
  {
    textArea.append("\n" + newText);
    textArea.repaint();
  }
}
